### ISSUE TITLE
rd-docker "força" o nome do container principal ser "web"

### ISSUE THREAD

**Issue by caiobonfante** [ResultadosDigitais/rd-docker#4]
Como pode ser visto nos comandos start e console:
```
start | s)
    echo_command "Starting web application"
    execute_command "web" "/var/app/entrypoint.sh"
    exit 0
    ;;

  console | c)
    echo_command "Starting up TTY Session on main container"
    execute_command "web" "bash"
    exit 0
    ;;
```
Caso seja definido um nome diferente de "web" para o container principal no 
`docker-compose.yml` de algum projeto que esteja utilizando a script `rd-docker`, os comandos acima não funcionarão

**Comment by geisonbiazus** [comment]
Thanks! I forgot to use the config there.
